### ISSUE TITLE
Mode()

### ISSUE THREAD

**Issue by DylanMeeus** [DylanMeeus/hasgo#3]
Return the item with the highest frequency

**Comment by xcgpseud** [comment]
Working on implementation now, idea is to return SliceType with results as opposed to ElementType, due to potential of several results.

|input|expected output|
|---|---|
|[1, 2, 3]|[]|
|[1, 2, 2, 3]|[2]|
|[1, 2, 2, 3, 3]|[2, 3]|

**Comment by DylanMeeus** [comment]
Implemented in #49
