### ISSUE TITLE
Maximum / Minimum with custom comparator predicate

### ISSUE THREAD

**Issue by Naviigator** [DylanMeeus/hasgo#47]
Return the maximum / minimum value in a list, decided by the comparator predicate
[a] -> (a, a -> int) -> a

**Comment by DylanMeeus** [comment]
Good idea, in haskell these are:
```haskell
maximumBy :: Foldable t => (a -> a -> Ordering) -> t a -> a 
minimumBy :: Foldable t => (a -> a -> Ordering) -> t a -> a 
```

Thanks!

**Comment by DylanMeeus** [comment]
Added a rudimentary function for which both can be expressed for now. But which should be refactored once Reducers / Folders are in place.
