### ISSUE TITLE
Drop function

### ISSUE THREAD

**Issue by xcgpseud** [DylanMeeus/hasgo#76]
Implement the drop function:

drop :: Int -> [a] -> [a]

drop n xs returns the suffix of xs after the first n elements, or [] if n > length xs:

```haskell
drop 6 "Hello World!" == "World!"
drop 3 [1,2,3,4,5] == [4,5]
drop 3 [1,2] == []
drop 3 [] == []
drop (-1) [1,2] == [1,2]
drop 0 [1,2] == [1,2]
```

**Comment by DylanMeeus** [comment]
Implemented in #77
