### ISSUE TITLE
Nub

### ISSUE THREAD

**Issue by DylanMeeus** [DylanMeeus/hasgo#9]
Haskell nub (unique) function

**Comment by xcgpseud** [comment]
| Function     | Signature                   | String | Number | Struct | Description |
|------------  | --------------------------  | :----: | :----: | :----: | ----------- |
| `Nub`        | `[a] -> [a]`                |   ✓    |   ✓    |    ✓   | Returns a Slice containing one of each of the input elements |

|Input|Output|
|:---:|:---:|
|Ints{1, 2, 3, 2, 1}|Ints{1, 2, 3}|
